apiVersion: apps/v1
kind: Deployment
metadata:
  name: depgraph
spec:
  selector:
    matchLabels:
      app: depgraph
  replicas: 2
  template:
    metadata:
      labels:
        app: depgraph
    spec:
      containers:
        - name: app
          image: "registry.kube.zero.haus/depgraph:latest"
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: depgraph-service
  labels:
    name: depgraph-service
spec:
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
  selector:
    app: depgraph
  type: ClusterIP
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: depgraph
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/issuer: "letsencrypt-prod"
spec:
  tls:
  - hosts:
    - depgraph.kube.zero.haus
    secretName: depgraph-tls
  rules:
  - host: depgraph.kube.zero.haus
    http:
      paths:
      - path: /
        backend:
          serviceName: depgraph-service
          servicePort: 80
